name: Bump Version Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to fetch tags

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          latest=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest"
          echo "latest_tag=$latest" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_version
        run: |
          tag=${{ steps.get_tag.outputs.latest_tag }}
          major=$(echo $tag | cut -d. -f1 | tr -d v)
          minor=$(echo $tag | cut -d. -f2)
          patch=$(echo $tag | cut -d. -f3)
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.bump_version.outputs.new_tag }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ steps.bump_version.outputs.new_tag }}
